name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Demo LS on VPS
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          cd public_html/democd/ 
          git clone https://github.com/Thibault-lvrn/Back-TD1.git
          cd Back-TD1
          git pull
          composer install
          php bin/console c:c
